version: '3.8'

services:
  aums-api:
    build: .
    container_name: aums-api
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/app
    command: npm run dev
    working_dir: /app

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
    - pgadmin_data:/var/lib/pgadmin


volumes:
  postgres_data:
  pgadmin_data:  
